language: node_js
notifications:
  email: false
cache:
  directories:
  - node_modules
node_js:
  - "4.2"
script:
  - gulp build
before_deploy:
    - cd build
deploy:
  provider: heroku
  api_key:
    secure: "26f01ce9-f060-47ec-b7f3-cb1a58438559"
  skip_cleanup: true