language: node_js
notifications:
  email: false
cache:
  directories:
  - node_modules
node_js:
  - "4.2"
script:
  - gulp build
after_success:
  # Turn off warnings about SSH keys:
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  # Clear your current Heroku SSH keys:
  - heroku keys:clear
  # Add a new SSH key to Heroku
  - yes | heroku keys:add
  # Clone Heroku deployment repo to dist folder
  - git clone git@heroku.com:static-in-dynamic-for-heroku.git build
  # Build
  - grunt build
  # Commit and Push dist folder to Heroku
  - cd dist
  - git config --global user.name "Webmaster"
  - git config --global user.email "webmaster.alfamed@gmail.com"
  - git add *
  - git commit -am "Travis CI"
  - git push origin master
env:
  global:
    secure: 26f01ce9-f060-47ec-b7f3-cb1a58438559
before_deploy:
    - ls -la
deploy:
  provider: heroku
  api_key:
    secure: "26f01ce9-f060-47ec-b7f3-cb1a58438559"
  skip_cleanup: true